// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'elixir': string;
  'html': string;
  'java': string;
  'javascript': string;
  'scss': string;
  'swift': string;
  'tag': string;
  'typescript': string;
}
export const cssExports: CssExports;
export default cssExports;
