// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footerIcon': string;
  'footerIconWithCount': string;
  'footerTimestamp': string;
  'userPost': string;
  'userPostAvatar': string;
  'userPostFooter': string;
  'userPostName': string;
  'userPostUserDetails': string;
}
export const cssExports: CssExports;
export default cssExports;
