// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flexCol': string;
  'flexRow': string;
  'userInfo': string;
  'userInfoAlias': string;
  'userInfoAvatarContainer': string;
  'userInfoButtonSelection': string;
  'userInfoContentContainer': string;
  'userInfoName': string;
  'userInfoNameAlias': string;
  'userInfotopDetails': string;
}
export const cssExports: CssExports;
export default cssExports;
