// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alias': string;
  'avatar': string;
  'bottomRow': string;
  'container': string;
  'editProfile': string;
  'fullName': string;
  'middleRow': string;
  'topButton': string;
  'topLine': string;
  'topRow': string;
}
export const cssExports: CssExports;
export default cssExports;
