// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acceptEdit': string;
  'editForm': string;
  'editFormHover': string;
  'formDefault': string;
  'isEditing': string;
  'overlay': string;
  'rejectEdit': string;
}
export const cssExports: CssExports;
export default cssExports;
