// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abutton': string;
  'articleContainer': string;
  'bottomButtons': string;
  'button': string;
  'icon': string;
  'infoContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
