// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'borderNone': string;
  'borderRound': string;
  'colorPrimary': string;
  'colorSecondary': string;
  'colorUnavailable': string;
}
export const cssExports: CssExports;
export default cssExports;
