// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeIcon': string;
  'container': string;
  'container-inForm': string;
  'container-inPost': string;
  'linkDomain': string;
  'linkIcon': string;
  'linkImage': string;
  'linkImage-inForm': string;
  'linkImage-inPost': string;
  'linkTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
