

//SESSION
export let AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export let AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export let AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export let LOGOUT = 'LOGOUT';

//SUBSCRIPTIONS
export let PENDING_SUBSCRIPTION_REQUESTS = 'PENDING_SUBSCRIPTION_REQUESTS';
