//SESSION
export let AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export let AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export let AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export let LOGOUT = 'LOGOUT';

//FEED
export const GET_GLOBAL_FEED = 'GET_GLOBAL_FEED';
export const GET_GLOBAL_FEED_SUCCESS = 'GET_GLOBAL_FEED_SUCCESS';
export const GET_GLOBAL_FEED_FAIL = 'GET_GLOBAL_FEED_FAIL';

export const GET_PROFILE_FEED = 'GET_PROFILE_FEED';
export const GET_PROFILE_FEED_SUCCESS = 'GET_PROFILE_FEED_SUCCESS';
export const GET_PROFILE_FEED_FAIL = 'GET_PROFILE_FEED_FAIL';

// FOLLOWERS
export let GET_ACCEPTED_FOLLOWERS = 'GET_FOLLOWERS';
export let GET_ACCEPTED_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export let GET_ACCEPTED_FOLLOWERS_FAILURE = 'GET_FOLLOWERS_SUCCESS';
export let GET_PENDING_FOLLOW_REQUESTS = 'GET_PENDING_FOLLOW_REQUESTS';
export let GET_PENDING_FOLLOW_REQUESTS_SUCCESS = 'GET_PENDING_REQUESTS_SUCCESS';
export let GET_PENDING_FOLLOW_REQUESTS_FAILURE = 'GET_PENDING_FOLLOW_REQUESTS_FAILURE';
export let ACCEPT_FOLLOW_REQUEST = 'ACCEPT_FOLLOW_REQUEST';
export let ACCEPT_FOLLOW_REQUEST_SUCCESS = 'ACCEPT_FOLLOW_REQUEST_SUCCESS';
export let ACCEPT_FOLLOW_REQUEST_FAILURE = 'ACCEPT_FOLLOW_REQUEST_FAILURE';
export let REJECT_FOLLOW_REQUEST = 'REJECT_FOLLOW_REQUEST';
export let REJECT_FOLLOW_REQUEST_SUCCESS = 'REJECT_FOLLOW_REQUEST_SUCCESS';
export let REJECT_FOLLOW_REQUEST_FAILURE = 'REJECT_FOLLOW_REQUEST_FAILURE';

// UPDATE GLOBAL OBJECTS
export let GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export let GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export let NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export let APPEND_GLOBAL_FEED = 'APPEND_GLOBAL_FEED';
export let APPEND_NEW_POST_TO_GLOBAL_FEED = 'APPEND_NEW_POST_TO_GLOBAL_FEED';
export let APPEND_NEW_USERS = 'APPEND_NEW_USERS';
export let APPEND_NEW_POSTS = 'APPEND_NEW_POSTS';

export let SUBSCRIPTION_REQUEST_SUCCESS = 'SUBSCRIPTION_REQUEST_SUCCESS';
export let UPDATE_FOLLOWER_REQUESTS_SUCCESS = 'UPDATE_FOLLOWER_REQUESTS_SUCCESS';

// SUBSCRIPTION
export let GET_PENDING_SUBSCRIPTION_REQUESTS = 'GET_PENDING_SUBSCRIPTION_REQUESTS';
export let GET_PENDING_SUBSCRIPTION_REQUESTS_SUCCESS = 'GET_PENDING_SUBSCRIPTION_REQUESTS_SUCCESS';
export let GET_PENDING_SUBSCRIPTION_REQUESTS_FAIL = 'GET_PENDING_SUBSCRIPTION_REQUESTS_FAIL';
export let GET_ACCEPTED_SUBSCRIPTION_REQUESTS = 'GET_ACCEPTED_SUBSCRIPTION_REQUESTS';
export let GET_ACCEPTED_SUBSCRIPTION_REQUESTS_SUCCESS = 'GET_ACCEPTED_SUBSCRIPTION_REQUESTS_SUCCESS';
export let GET_ACCEPTED_SUBSCRIPTION_REQUESTS_FAIL = 'GET_ACCEPTED_SUBSCRIPTION_REQUESTS_FAIL';

// LIKES
export let GET_LIKED_POSTS_SUCCESS = 'GET_LIKED_POSTS_SUCCESS';
export let LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export let UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS';
