export let GET_ACCEPTED_FOLLOWERS = 'GET_FOLLOWERS';
export let GET_ACCEPTED_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export let GET_ACCEPTED_FOLLOWERS_FAILURE = 'GET_FOLLOWERS_SUCCESS';
export let GET_PENDING_FOLLOW_REQUESTS = 'GET_PENDING_FOLLOW_REQUESTS';
export let GET_PENDING_FOLLOW_REQUESTS_SUCCESS = 'GET_PENDING_REQUESTS_SUCCESS';
export let GET_PENDING_FOLLOW_REQUESTS_FAILURE = 'GET_PENDING_FOLLOW_REQUESTS_FAILURE';


export let ACCEPT_FOLLOW_REQUEST = 'ACCEPT_FOLLOW_REQUEST';
export let ACCEPT_FOLLOW_REQUEST_SUCCESS = 'ACCEPT_FOLLOW_REQUEST_SUCCESS';
export let ACCEPT_FOLLOW_REQUEST_FAILURE = 'ACCEPT_FOLLOW_REQUEST_FAILURE';
export let REJECT_FOLLOW_REQUEST = 'REJECT_FOLLOW_REQUEST';
export let REJECT_FOLLOW_REQUEST_SUCCESS = 'REJECT_FOLLOW_REQUEST_SUCCESS';
export let REJECT_FOLLOW_REQUEST_FAILURE = 'REJECT_FOLLOW_REQUEST_FAILURE';
