export let GET_FOLLOWERS = 'GET_FOLLOWERS';
export let GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export let GET_FOLLOWERS_FAILURE = 'GET_FOLLOWERS_SUCCESS';
export let UPDATE_FOLLOWER_REQUEST = 'UPDATE_FOLLOWER_REQUEST';
export let UPDATE_FOLLOWER_REQUEST_SUCCESS = 'UPDATE_FOLLOWER_REQUEST_SUCCESS';
export let UPDATE_FOLLOWER_REQUEST_FAILURE = 'UPDATE_FOLLOWER_REQUEST_FAILURE';
