export let GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export let GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export let NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export let APPEND_GLOBAL_FEED = 'APPEND_GLOBAL_FEED';
