//export let AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';

export let SUBSCRIPTION_REQUEST_SUCCESS = 'SUBSCRIPTION_REQUEST_SUCCESS';
export let GET_PENDING_SUBSCRIPTION_REQUESTS_SUCCESS = 'GET_PENDING_SUBSCRIPTION_REQUESTS_SUCCESS';
export let UPDATE_SUBSCRIPTION_REQUESTS_SUCCESS = 'UPDATE_SUBSCRIPTION_REQUESTS_SUCCESS';
export let DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export let FOLLOW_REQUEST_SUCCESS = 'FOLLOW_REQUEST_SUCCESS';
export let GET_PENDING_FOLLOW_REQUESTS_SUCCESS = 'GET_PENDING_FOLLOW_REQUESTS_SUCCESS';
export let UPDATE_FOLLOWER_REQUESTS_SUCCESS = 'UPDATE_FOLLOWER_REQUESTS_SUCCESS';
export let GET_ACCEPTED_FOLLOW_REQUESTS_SUCCESS = 'GET_ACCEPTED_FOLLOW_REQUESTS_SUCCESS';
export let GET_NEW_FOLLOWERS = 'GET_NEW_FOLLOWERS';
export let GET_NEW_FOLLOWERS_SUCCESS = 'GET_NEW_FOLLOWERS_SUCCESS';
export let GET_NEW_FOLLOWERS_FAIL = 'GET_NEW_FOLLOWERS_FAIL';
