// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accountInfo': string;
  'accountName': string;
  'logoutButton': string;
}
export const cssExports: CssExports;
export default cssExports;
