// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemHover': string;
  'showMore': string;
  'title': string;
  'widgetContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
