// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aboutDescription': string;
  'avatar': string;
  'container': string;
  'footer': string;
  'gitHubIcon': string;
  'linkedInIcon': string;
  'logoIcon': string;
  'nameAndSubheader': string;
  'tags': string;
  'techStack': string;
}
export const cssExports: CssExports;
export default cssExports;
