// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editContainer': string;
  'editImageContainer': string;
  'editInProgressBackground': string;
  'editUploader': string;
  'plusIcon': string;
  'poop': string;
  'uploadPlaceholder': string;
  'uploaded_image': string;
}
export const cssExports: CssExports;
export default cssExports;
