// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inboxList': string;
  'noHeaderBottomBord': string;
  'topTabs': string;
}
export const cssExports: CssExports;
export default cssExports;
