// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'subscribeBtn': string;
  'unsubscribe': string;
}
export const cssExports: CssExports;
export default cssExports;
