// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'stylePrimary': string;
  'styleSecondary': string;
}
export const cssExports: CssExports;
export default cssExports;
