// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mainCenter': string;
  'mainContainer': string;
  'mainRight': string;
}
export const cssExports: CssExports;
export default cssExports;
