// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'previewButton': string;
  'userPreview': string;
  'userPreviewButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
