// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tab': string;
  'tabContent': string;
  'tabHeaderItemFocused': string;
}
export const cssExports: CssExports;
export default cssExports;
