// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tabContainer': string;
  'tabHeader': string;
  'tabHeaderItem': string;
  'tabHeaderItemFocused': string;
}
export const cssExports: CssExports;
export default cssExports;
