// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'fullscreenBackground': string;
  'hide': string;
  'postForm': string;
  'postFormNav': string;
}
export const cssExports: CssExports;
export default cssExports;
