// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'altLink': string;
  'login': string;
  'loginContainer': string;
  'loginForm': string;
}
export const cssExports: CssExports;
export default cssExports;
