// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'postForm': string;
  'postFormAvatar': string;
  'postFormContent': string;
  'postFormFooter': string;
  'postFormInput': string;
  'postFormSubmit': string;
  'profile-image-alias': string;
}
export const cssExports: CssExports;
export default cssExports;
