// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'articleHeader': string;
  'articlePreview': string;
  'author': string;
  'date': string;
  'infoContainer': string;
  'whiteTextBackground': string;
}
export const cssExports: CssExports;
export default cssExports;
