// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'navContainer': string;
  'navItem': string;
  'navItemIcon': string;
  'navItemSelected': string;
  'navItemText': string;
  'navPostBtn': string;
  'navPostContainer': string;
  'navPostIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
