// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item_category': string;
  'item_mentions': string;
  'item_title': string;
  'trendingContainer': string;
  'trendingRightContainer': string;
  'trending_item2': string;
  'trending_show_more': string;
}
export const cssExports: CssExports;
export default cssExports;
