// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authError': string;
  'error': string;
  'errorField': string;
  'errorText': string;
  'formFields': string;
  'label': string;
  'labelFocused': string;
  'signUpFieldColumns': string;
  'submitButton': string;
  'textField': string;
  'textFieldWithError': string;
}
export const cssExports: CssExports;
export default cssExports;
